version: "0.0"
services:
  db:
    image:  mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: toor
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
endpoints:
  db:
    - path: /
      service: db
      port: 3306